### ISSUE TITLE
`no-multiple-resolved` rule in ESLint 9.3.0: TypeError: Cannot read properties of undefined (reading 'map')

### ISSUE THREAD

**Issue by zloirock** [eslint-community/eslint-plugin-promise#472]
After updating `eslint` to 9 (9.3.0), `eslint-plugin-promise@6.2.0` cause:
```
Oops! Something went wrong! :(

ESLint: 9.3.0

TypeError: Cannot read properties of undefined (reading 'map')
Occurred while linting /***/core-js/scripts/usage/usage.mjs:34
Rule: "promise/no-multiple-resolved"
    at CodePathInfo.getCurrentSegmentInfos (/***/core-js/tests/eslint/node_modules/eslint-plugin-promise/rules/no-multiple-resolved.js:147:38)
    at CallExpression > Identifier.callee (/***/core-js/tests/eslint/node_modules/eslint-plugin-promise/rules/no-multiple-resolved.js:464:48)
    at ruleErrorHandler (/***/core-js/tests/eslint/node_modules/eslint/lib/linter/linter.js:1115:48)
    at /***/core-js/tests/eslint/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/***/core-js/tests/eslint/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/***/core-js/tests/eslint/node_modules/eslint/lib/linter/node-event-generator.js:297:26)
    at NodeEventGenerator.applySelectors (/***/core-js/tests/eslint/node_modules/eslint/lib/linter/node-event-generator.js:326:22)
    at NodeEventGenerator.enterNode (/***/core-js/tests/eslint/node_modules/eslint/lib/linter/node-event-generator.js:340:14)
    at runRules (/***/core-js/tests/eslint/node_modules/eslint/lib/linter/linter.js:1154:40)
```

![image](https://github.com/eslint-community/eslint-plugin-promise/assets/2213682/ea3f9a00-ae40-4b11-8d1b-d20037f76bac)

The error present only in `promise/no-multiple-resolved` rule.

**Comment by zloirock** [comment]
https://github.com/eslint/eslint/issues/17457
https://github.com/eslint/eslint/pull/17936
